platform: linux

image_resource:
  type: docker-image
  source:
    repository: microsoft/dotnet

inputs:
- name: nupkg-app
  
outputs:
- name: nupkg-app/nuget-task-output


run:
  path: sh
  args: ["nupkg-app/ci/build.sh"]
