resource_types:
- name: nexus-repo-nuget
  type: docker-image
  source:
    repository: docker-registry-gdc.axadmin.net/nexus-repo-nuget

resources:
- name: nupkg-app
  type: git
  source:
    uri: https://github.com/Alexvianet/nupkg-app.git
    branch: master

- name: nexus-nuget
  type: nexus-repo-nuget
  source:
    repository: nuget-public
    package: dotnetapp

jobs:
- name: build-and-save-to-artifactory
  plan:
  - get: nupkg-app
  - task: build-nupkg-app
    file: build.yml
  - put: file-repository
    params: { file: ./nupkg-app/ }

- name: trigger-when-new-file-is-added-to-artifactory
  serial: true
  public: true
  plan:
  - get: nupkg-app
    passed:
      - build-and-save-to-artifactory
  - task: use-new-file
    file: build.yml
  - put: file-repository
    params: { file: ./nupkg-app/ }