resource_types:
- name: nexus-repo-nuget
  type: docker-image
  source:
    repository: docker-registry-gdc.axadmin.net/nexus-repo-nuget
    insecure_registries: [docker-registry-gdc.axadmin.net]
    username: gdc
    password: ueUAEN234!!+!aA
resources:
- name: nupkg-app
  type: git
  source:
    uri: https://github.com/Alexvianet/nupkg-app.git
    branch: master

- name: nexus-nuget
  type: nexus-repo-nuget
  source:
    repository: nuget-public
    package: dotnetapp
    nugetApiKey: 64b36f6e-f794-3850-9252-3c25ec8698e1

jobs:
- name: build-and-save-to-artifactory
  plan:
  - get: nupkg-app
    trigger: true
  - task: build-nupkg-app
    file: nupkg-app/build.yml
    params:
      version: 1.1.0
  - put: nexus-nuget
    params: { folder: ./nuget-task-output/ }
- name: trigger-when-new-version-is-added-to-artifactory
  plan:
  - get: nexus-nuget
    passed:
      - build-and-save-to-artifactory
    trigger: true
  - get: nupkg-app
  - task: use-new-file
    file: nupkg-app/build.yml
    params:
      version: 1.1.1
  - put: nexus-nuget
    params: { folder: ./nuget-task-output/ }