resources:
- name: HelloWorldDotNetCore
  type: git
  source:
    uri: https://github.com/Alexvianet/HelloWorldDotNetCore.git
    branch: master

jobs:
- name: hello-world-app
  plan:
  - get: HelloWorldDotNetCore
    trigger: true
  - task: tests
    file: HelloWorldDotNetCore/build.yml
